# General server settings
server:
    host: 0.0.0.0
    port: 9001
    debug: True

# OpenAPI specs
openapi:
    tes: mock_tes/specs/schema.task_execution_service.d55bf88.openapi.modified.yaml
    cost_update: mock_tes/specs/schema.task_execution_service.config_update.openapi.yaml

# TES service settings
task_info:
    currency: BTC
    unit_costs:  # per min
        cpu_usage: 0.01  # per core and second
        memory_consumption: 0.01  # per GB and second
        data_storage: 1  # per GB
        data_transfer: 0.01  # per GB and 1000 km
