paths:
  /update-config:
    post:
      summary: Update task info config
      operationId: UpdateTaskInfoConfig
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/tesTaskInfoConfig'
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/tesTaskInfoConfig'
          required: true
          description: ''
      tags:
        - TaskService
      x-swagger-router-controller: ga4gh.tes.server
definitions:
  tesTaskInfoConfig:
    type: object
    properties:
      currency:
        type: string
        enum:
          - AUD
          - BRL
          - BTC
          - CAD
          - CHF
          - CNH
          - EUR
          - GBP
          - HKD
          - INR
          - KRW
          - JPY
          - MXN
          - NOK
          - NZD
          - RUB
          - SEK
          - SGD
          - TRY
          - USD
          - ZAR
        description: Currency/unit of the costs.
      unit_costs:
        $ref: '#/definitions/tesTaskInfoCosts'
  tesTaskInfoCosts:
    type: object
    properties:
      cpu_usage:
        type: number
        format: double
        description: costs per core
      memory_consumption:
        type: number
        format: double
        description: costs of computation per GB
      data_storage:
        type: number
        format: double
        description:  cost of data storage  GB
      data_transfer:
        type: number
        format: double
        description: cost of data transfer per GB and 1000 km