paths:
  /update-config:
    post:
      summary: Update task info config
      operationId: UpdateTaskInfoConfig
      responses:
        '200':
          description: ''
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/tesTaskInfoConfig'
          required: true
          description: ''
      tags:
        - TaskService
      x-swagger-router-controller: ga4gh.tes.server
definitions:
  tesTaskInfoConfig:
    type: object
    properties:
      currency:
        type: string
        enum: 
          - ARBITRARY
          - BTC
          - EUR
          - USD
        description: Currency/unit of the costs.
      time_unit:
        type: string
        enum:
          - SECONDS 
          - MINUTES
          - HOURS
        description: Unit of the queue time.
      unit_costs:
        $ref: '#/definitions/tesTaskInfoCosts'
  tesTaskInfoCosts:
    type: object
    properties:
      cpu_usage:
        type: integer
        format: int64
        description: costs per core
      memory_consumption:
        type: integer
        format: int64
        description: costs of computation per GB
      data_storage:
        type: integer
        format: int64
        description:  cost of data storage  GB
      data_transfer:
        type: integer
        format: int64
        description: cost of data transfer per GB and 1000 km