# General server settings
server:
    host: localhost
    port: 9001
    debug: True

# OpenAPI specs
openapi:
    path: specs/schema.task_execution_service.d55bf88.openapi.modified.yaml'

# TES service info settings
task_info:
    currency: ARBITRARY
    time_unit: HOURS
    size_unit: GB
    unit_costs_per_time_unit:
        computation_costs_per_unit: 1
        memory_costs_per_size_unit: 1
        data_storage_per_size_unit: 1
        data_transfer_per_size_unit: 1